// Baseball_Management/src/components/FormulariosCRUD/DirectionTeamCRUD.jsx

import React, { useState, useEffect } from "react";
import BaseCRUD from "./BaseCRUD";
import { Network, ShieldCheck, Building2, ClipboardList } from "lucide-react";
import { makeCountKpi, makeStatusKpi, makeBrandKpi } from "./kpiDefs";

const DirectionTeamCRUD = () => {
    const [teams, setTeams] = useState([]);

    // Obtener los equipos
    const fetchTeams = async () => {
        try {
            const response = await fetch("http://127.0.0.1:8000/teams/");
            if (response.ok) {
                const data = await response.json();
                setTeams(data.map(team => ({ id: team.id, name: team.name })));
            }
        } catch (error) {
            console.error("Error obteniendo equipos:", error);
        }
    };

    useEffect(() => {
        fetchTeams();
    }, []);

    const fields = [
        { name: "id", label: "ID", type: "number", autoGenerated: true },
        { 
            name: "Team_id", 
            label: "Equipo", 
            type: "select", 
            options: teams 
        },
    ];

    const apiUrl = "http://127.0.0.1:8000/direction-teams/";
    const initialFormValues = {
        id: "",
        Team_id: "",
    };

    const kpis = [
        makeCountKpi("Total Equipos Dirección", Network, { sub: 'equipos asignados', tone: 'amber' }),
        makeStatusKpi("Estado", ShieldCheck, { tone: 'green' }),
        makeBrandKpi("Organización", Building2, 'ACTIVA', { sub: 'estructura vigente', tone: 'green' }),
        makeCountKpi("Registros", ClipboardList, { sub: 'por página', tone: 'amber' }),
    ];

    const subtitle = "Equipos de dirección: estructura organizativa de cada franquicia.";

    return (
        <BaseCRUD
            apiUrl={apiUrl}
            fields={fields}
            title="Equipos de Dirección"
            initialFormValues={initialFormValues}
            kpis={kpis}
            subtitle={subtitle}
        />
    );
};

export default DirectionTeamCRUD;