// Baseball_Management/src/components/FormulariosCRUD/ScoreCRUD.jsx

import React, { useState, useEffect } from "react";
import BaseCRUD from "./BaseCRUD";

const ScoreCRUD = () => {

    const [teams, setTeams] = useState([]);

    // Obtener los equipos
    const fetchTeams = async () => {
        try {
            const response = await fetch("http://127.0.0.1:8000/teams/");
            if (response.ok) {
                const data = await response.json();
                setTeams(data.map(team => ({ id: team.id, name: team.name })));
            }
        } catch (error) {
            console.error("Error obteniendo equipos:", error);
        }
    };

    useEffect(() => {
        fetchTeams();
    }, []);

    const fields = [
        { name: "id", label: "ID", type: "number", nullable: false, autoGenerated: true },
        { 
            name: "winner", 
            label: "Ganador", 
            type: "select", 
            options: teams,
            nullable: false 
        },
        { 
            name: "loser", 
            label: "Perdedor", 
            type: "select", 
            options: teams,
            nullable: false 
        },
        { name: "w_points", label: "Puntos del Ganador", type: "number", nullable: false },
        { name: "l_points", label: "Puntos del Perdedor", type: "number", nullable: false },
    ];
    const apiUrl = "http://127.0.0.1:8000/scores/";
    const initialFormValues = {
        id: "",
        winner: "",
        loser: "",
        w_points: "",
        l_points: "",
    };

    return (
        <BaseCRUD
            apiUrl={apiUrl}
            fields={fields}
            title="Marcadores"
            initialFormValues={initialFormValues}
        />
    );
};
export default ScoreCRUD;


