// Baseball_Management/src/components/FormulariosCRUD/SeasonCRUD.jsx

import React from "react";
import BaseCRUD from "./BaseCRUD";
import { Calendar, ShieldCheck, RotateCcw, ClipboardList } from "lucide-react";
import { makeCountKpi, makeStatusKpi, makeBrandKpi } from "./kpiDefs";

const SeasonCRUD = () => {
    const fields = [
        { name: "id", label: "ID", type: "number", autoGenerated: true },
        { name: "name", label: "Nombre", type: "text" },
    ];
    const apiUrl = "http://127.0.0.1:8000/seasons/";
    const initialFormValues = {
        id : "",
        name: "",
    };

    const kpis = [
        makeCountKpi("Total Temporadas", Calendar, { sub: 'temporadas registradas', tone: 'amber' }),
        makeStatusKpi("Estado", ShieldCheck, { tone: 'green' }),
        makeBrandKpi("Ciclo Deportivo", RotateCcw, 'ACTIVO', { sub: 'temporada en curso', tone: 'green' }),
        makeCountKpi("Registros", ClipboardList, { sub: 'por página', tone: 'amber' }),
    ];

    const subtitle = "Temporadas del campeonato: definición de ciclos deportivos.";

    return (
        <BaseCRUD
          apiUrl={apiUrl}
          fields={fields}
          title="Temporadas"
          initialFormValues={initialFormValues}
          kpis={kpis}
          subtitle={subtitle}
        />
    );
};
export default SeasonCRUD;

