// Baseball_Management/src/components/FormulariosCRUD/TeamOnTheFieldCRUD.jsx

import React, { useState, useEffect } from "react";
import BaseCRUD from "./BaseCRUD";

const TeamOnTheFieldCRUD = () => {
    const [lineups, setLineups] = useState([]);

    // Obtener las alineaciones
    const fetchLineups = async () => {
        try {
            const response = await fetch("http://127.0.0.1:8000/lineups/");
            if (response.ok) {
                const lineupData = await response.json();
                const teamsNames = await Promise.all(
                    lineupData.map(async (lineup) => {
                        const teamsResponse = await fetch(`http://127.0.0.1:8000/teams/${lineup.team_id}/`);
                        if (teamsResponse.ok) {
                            const team = await teamsResponse.json();
                            return { id: lineup.id, name: `${team.name} - ${lineup.id}`};
                        }
                    })
                );
                setLineups(teamsNames);
            };
        } catch (error) {
            console.error("Error obteniendo alineaciones:", error);
        }
    };

    useEffect(() => {
        fetchLineups();
    }, []);

    const fields = [
        { 
            name: "id", 
            label: "ID", 
            type: "number", 
            autoGenerated: true 
        },
        { 
            name: "lineup_id", 
            label: "Alineación", 
            type: "select", 
            options: lineups, 
            nullable: false 
        },
    ];

    const apiUrl = "http://127.0.0.1:8000/teams-on-field/";
    const initialFormValues = {
        id: "",
        lineup_id: "",
    };

    return (
        <BaseCRUD
            apiUrl={apiUrl}
            fields={fields}
            title="Equipos en el Campo"
            initialFormValues={initialFormValues}
        />
    );
};

export default TeamOnTheFieldCRUD;


