"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
##SECRET_KEY = 'django-insecure-$*u=c%e_whg2lnk_h8-9ml_%2)f&bimcmqbz343d49z6v2c0$-'

# SECURITY WARNING: don't run with debug turned on in production!
##DEBUG = True

##ALLOWED_HOSTS = []
SECRET_KEY = config('SECRET_KEY', default='django-insecure-placeholder')

DEBUG = config('DEBUG', default=True, cast=bool)

# Detecta la ejecución del runner de tests (`manage.py test`). En modo test el
# cliente de Django no envía X-Forwarded-Proto, así que el bloque de transporte
# de abajo (SECURE_SSL_REDIRECT) redirigiría cada request a HTTPS (301) y la
# suite de integración fallaría aunque se corra con DEBUG=False (como en CI).
_TESTING = 'test' in sys.argv

# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')
# En producción (Render/Railway/*.onrender.com) se pasan por env separados por comas.
ALLOWED_HOSTS = [
    h.strip()
    for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
    if h.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'db_structure.apps.DbStructureConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_extensions',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        # Neon (serverless free) exige sslmode=require en producción.
        'OPTIONS': {'sslmode': config('DB_SSLMODE', default='prefer')},
    }
    
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.FlexibleTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny', 
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
    'DEFAULT_THROTTLE_RATES': {
        # En dev/tests el límite es alto (evita falsos 429 en el runner de
        # integración, que comparte IP/proceso y corre con DEBUG=False en CI);
        # en producción real se endurece para frenar fuerza bruta de login.
        'login': '8/min' if (not DEBUG and not _TESTING) else '500/min',
    },

}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    # 'django.contrib.auth.hashers.Argon2PasswordHasher',   # Para una encriptación más segura
    # 'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    # 'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    # 'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',

    'django.contrib.auth.hashers.PBKDF2PasswordHasher',     # Encriptado por defecto
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

AUTH_USER_MODEL = 'api.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'
USE_I18N = True
USE_L10N = True
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False

# Formatos personalizados de entrada para fechas y horas
DATE_INPUT_FORMATS = ['%d/%m/%Y']  # Día/Mes/Año
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M:%S']  # Día/Mes/Año Hora:Minuto:Segundo



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Orígenes CORS permitidos: locales + los de producción (env, separados por comas).
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # React frontend
    'http://127.0.0.1:3000',
] + [
    o.strip()
    for o in config('CORS_ALLOWED_ORIGINS', default='').split(',')
    if o.strip()
]


STATIC_URL = 'static/'
# Sirviendo React desde Django temporalmente para producción
#STATICSFILES_DIRS = [BASE_DIR / "frontend" / "build" / "static"]

# Media files (fotos de jugadores, etc.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Seguridad de transporte: solo se activan en producción (Render/Nginx terminan SSL y
# envían X-Forwarded-Proto). Localmente (http://localhost) se mantienen desactivadas
# y en modo test (CI, `manage.py test ...`) se omiten porque el cliente de test no
# envía X-Forwarded-Proto y SECURE_SSL_REDIRECT devolvería 301 en cada request.
if not DEBUG and not _TESTING:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True