# Generated by Django 5.1.4 on 2025-01-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='db_structure_user',
        ),
    ]
