# Generated by Django 5.1.3 on 2026-09-03 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='score',
            name='check_winner_not_equal_loser',
        ),
        migrations.RemoveConstraint(
            model_name='score',
            name='check_w_points_gte_l_points',
        ),
        migrations.RemoveConstraint(
            model_name='series',
            name='check_init_date_before_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='check_td_not_null_when_rol_2',
        ),
        migrations.AlterField(
            model_name='person',
            name='CI',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='dominant_hand',
            field=models.CharField(choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha'), ('ambas', 'Ambas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='playerswap',
            name='new_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_player_swap', to='db_structure.baseballplayer'),
        ),
        migrations.AlterField(
            model_name='playerswap',
            name='old_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_player_swap', to='db_structure.baseballplayer'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='type',
            field=models.CharField(choices=[('Director Técnico', 'Director Técnico'), ('Admin', 'Admin'), ('Usuario General', 'Usuario  General')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='TD_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_structure.technicaldirector'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('winner', models.F('loser')), _negated=True), name='Ganador y Perdedor deben ser diferente'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('w_points__gte', models.F('l_points'))), name='Los puntos del ganador deben ser mayores o iguales a los del perdedor'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('init_date__lt', models.F('end_date'))), name='La fecha de inicio debe ser antes de la fecha de finalización'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rol_id', 2), _negated=True), models.Q(('TD_id__isnull', True), _negated=True), _connector='OR'), name='El rol no puede ser Director Técnico si el campo está vacío'),
        ),
    ]
