# Generated by Django 5.1.3 on 2024-12-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bpparticipation',
            name='primary_key_bp_participation',
        ),
        migrations.RemoveConstraint(
            model_name='starplayer',
            name='primary_key_star_player',
        ),
        migrations.RemoveField(
            model_name='bpparticipation',
            name='season',
        ),
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
        migrations.RemoveField(
            model_name='starplayer',
            name='season',
        ),
        migrations.RemoveField(
            model_name='teamonthefield',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='series',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_structure.season'),
        ),
        migrations.AddConstraint(
            model_name='bpparticipation',
            constraint=models.UniqueConstraint(fields=('BP_id', 'series'), name='primary_key_bp_participation'),
        ),
        migrations.AddConstraint(
            model_name='starplayer',
            constraint=models.UniqueConstraint(fields=('series', 'position'), name='primary_key_star_player'),
        ),
    ]
