# Generated by Django 5.1.3 on 2024-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0002_remove_bpparticipation_primary_key_bp_participation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionteam',
            name='TD_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='DT_id',
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='No_games_lost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='No_games_won',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='running_average',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rol_id', 2), _negated=True), models.Q(('TD_id__isnull', True), _negated=True), _connector='OR'), name='check_td_not_null_when_rol_2'),
        ),
    ]
