# Generated by Django 5.1.3 on 2026-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0003_notification_favoriteplayer_favoriteteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballplayer',
            name='home_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseballplayer',
            name='obp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baseballplayer',
            name='rbi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseballplayer',
            name='slg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baseballplayer',
            name='war',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='innings_pitched',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='strikeouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='whip',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerinposition',
            name='assists_of',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerinposition',
            name='bases_stolen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerinposition',
            name='double_plays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerinposition',
            name='fielding_pct',
            field=models.FloatField(default=0),
        ),
    ]
