# Generated by Django 5.1.3 on 2026-09-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0005_person_bio_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballplayer',
            name='bats',
            field=models.CharField(choices=[('R', 'Diestro'), ('L', 'Zurdo')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='baseballplayer',
            name='throws',
            field=models.CharField(choices=[('R', 'Diestro'), ('L', 'Zurdo')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
