# Generated by Django 5.1.3 on 2026-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_structure', '0006_baseballplayer_bats_baseballplayer_throws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='team',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slogan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
