// frontend/src/components/FormulariosCRUD.jsx

import React, { useState, useEffect } from "react";
import BaseCRUD from "./BaseCRUD";
import { LayoutList, ShieldCheck, Shield, ClipboardList } from "lucide-react";
import { makeCountKpi, makeStatusKpi, makeBrandKpi } from "./kpiDefs";

const LineUpCRUD = () => {

    const [teams, setTeams] = useState([]);

    // Obtener los equipos
    const fetchTeams = async () => {
        try {
            const response = await fetch("http://127.0.0.1:8000/teams/");
            if (response.ok) {
                const data = await response.json();
                setTeams(data.map(team => ({ id: team.id, name: team.name })));
            }
        } catch (error) {
            console.error("Error obteniendo equipos:", error);
        }
    };

    useEffect(() => {
        fetchTeams();
    }, []);

    const fields = [
        { name: "id", label: "ID", type: "number", nullable: false, autoGenerated: true },
        { 
            name: "team_id", 
            label: "Equipo", 
            type: "select", 
            options: teams 
        },
    ];
    
    const apiUrl = "http://127.0.0.1:8000/lineups/";
    const initialFormValues = {
        id: "",
        team_id: "",
    };

    const kpis = [
        makeCountKpi("Total Alineaciones", LayoutList, { sub: 'alineaciones definidas', tone: 'amber' }),
        makeStatusKpi("Estado", ShieldCheck, { tone: 'green' }),
        makeBrandKpi("WBSC", Shield, 'CONFORME', { sub: 'reglamento vigente', tone: 'green' }),
        makeCountKpi("Registros", ClipboardList, { sub: 'por página', tone: 'amber' }),
    ];

    const subtitle = "Alineaciones titulares de cada equipo para los juegos del campeonato.";

    return (
        <BaseCRUD
            apiUrl={apiUrl}
            fields={fields}
            title="Alineaciones"
            initialFormValues={initialFormValues}
            kpis={kpis}
            subtitle={subtitle}
        />
    );
};
export default LineUpCRUD;


