// frontend/src/components/FormulariosCRUD/PositionCRUD.jsx

import React from "react";
import BaseCRUD from "./BaseCRUD";
import { Layers, ShieldCheck, Bookmark, ClipboardList } from "lucide-react";
import { makeCountKpi, makeStatusKpi, makeBrandKpi } from "./kpiDefs";

const PositionCRUD = () => {
    const fields = [
        { name: "id", label: "ID", type: "number", autoGenerated: true },
        { name: "name", label: "Nombre", type: "text", nullable: false },
    ];
    const apiUrl = "http://127.0.0.1:8000/positions/";
    const initialFormValues = {
        id: "",
        name: "",
    };

    const kpis = [
        makeCountKpi("Total Posiciones", Layers, { sub: 'posiciones del béisbol', tone: 'amber' }),
        makeStatusKpi("Configuración", ShieldCheck, { tone: 'green' }),
        makeBrandKpi("Catálogo", Bookmark, 'WBSC', { sub: 'normativa', tone: 'green' }),
        makeCountKpi("Registros", ClipboardList, { sub: 'por página', tone: 'amber' }),
    ];

    const subtitle = "Posiciones oficiales del béisbol según normativa WBSC.";

    return (
        <BaseCRUD
            apiUrl={apiUrl}
            fields={fields}
            title="Posiciones"
            initialFormValues={initialFormValues}
            kpis={kpis}
            subtitle={subtitle}
        />
    );
};
export default PositionCRUD;


