// frontend/src/components/FormulariosCRUD.jsx

import React from "react";
import BaseCRUD from "./BaseCRUD";
import { Key, ShieldCheck, Lock, ClipboardList } from "lucide-react";
import { makeCountKpi, makeStatusKpi, makeBrandKpi } from "./kpiDefs";

const RolCRUD = () => {
    const fields = [
        { name: "id", label: "ID", type: "number", autoGenerated: true },
        { name: "type", lable: "Tipo", type: "text"},
    ];
    const apiUrl = "http://127.0.0.1:8000/roles/";
    const initialFormValues = {
        id : "",
        type: "",
    };

    const kpis = [
        makeCountKpi("Total Roles", Key, { sub: 'roles definidos', tone: 'amber' }),
        makeStatusKpi("Estado", ShieldCheck, { tone: 'green' }),
        makeBrandKpi("Seguridad", Lock, 'HTTPS', { sub: 'control de acceso activo', tone: 'green' }),
        makeCountKpi("Registros", ClipboardList, { sub: 'por página', tone: 'amber' }),
    ];

    const subtitle = "Roles del sistema: Administrador, Director Técnico y Usuario General.";

    return (
        <BaseCRUD
          apiUrl={apiUrl}
          fields={fields}
          title="Roles"
          initialFormValues={initialFormValues}
          kpis={kpis}
          subtitle={subtitle}
        />
    );
};
export default RolCRUD;

