// frontend/src/components/FormulariosCRUD/TeamCRUD.jsx

import React from "react";
import BaseCRUD from "./BaseCRUD";
import { Trophy, ShieldCheck, Building2, LayoutGrid } from "lucide-react";
import { makeCountKpi, makeStatusKpi, makeBrandKpi } from "./kpiDefs";

const TeamCRUD = () => {
    const fields = [
        { name: "id", label: "ID", type: "number", autoGenerated: true },
        { name: "name", label: "Nombre", type: "text", nullable: false },
        { name: "color", label: "Color", type: "text", nullable: false },
        { name: "initials", label: "Iniciales", type: "text", nullable: false },
        { name: "representative_entity", label: "Entidad Representativa", type: "text", nullable: false },
    ];
    const apiUrl = "http://127.0.0.1:8000/teams/";
    const initialFormValues = {
        id: "",
        name: "",
        color: "",
        initials: "",
        representative_entity: "",
    };

    const kpis = [
        makeCountKpi("Total Equipos", Trophy, { sub: 'franquicias afiliadas', tone: 'amber' }),
        makeStatusKpi("Padrón Equipos", ShieldCheck, { tone: 'green' }),
        makeBrandKpi("Entidad Representativa", Building2, 'VERIFICADA', { sub: 'registro activo', tone: 'green' }),
        makeCountKpi("Equipos en Directorio", LayoutGrid, { sub: 'asignados', tone: 'amber' }),
    ];

    const subtitle = "Franquicias afiliadas al campeonato, colores oficiales y entidades representativas.";

    return (
        <BaseCRUD
            apiUrl={apiUrl}
            fields={fields}
            title="Equipos"
            initialFormValues={initialFormValues}
            kpis={kpis}
            subtitle={subtitle}
        />
    );
};
export default TeamCRUD;


