// Baseball_Management/src/components/FormulariosCRUD/BaseCRUD/CRUDForm.jsx

import React from "react";

const CRUDForm = ({
    fields,
    formValues,
    formErrors,
    onChange,
    onSave,
    onCancel,
}) => {

    return (
        <div className="item-form">
            <h2>{formValues.id ? "Editar" : "Crear"}</h2>
            {fields
                .filter((field) => !field.autoGenerated)
                .map((field) => (
                    <div className="form-group" key={field.name}>
                        <label>{field.label}:</label>
                        <input
                            type={field.type === "password" && field.showPassword ? "text" : field.type}
                            name={field.name}
                            value={formValues[field.name] || ""}
                            onChange={onChange}
                        />
                        {field.type === "password" && field.toggleVisibility && (
                            <button type="button" onClick={field.toggleVisibility}>
                                {field.showPassword ? "Ocultar" : "Mostrar"}
                            </button>
                        )}
                        {formErrors[field.name] && (
                            <div className="error-message">{formErrors[field.name][0]}</div>
                        )}
                    </div>
                ))}
            <div className="form-actions">
                <button onClick={onSave}>Guardar</button>
                <button onClick={onCancel}>Cancelar</button>
            </div>
        </div>
    );
};

export default CRUDForm;




