import React from "react";

const CRUDForm = ({
  fields,
  formValues,
  formErrors,
  onChange,
  onSave,
  onCancel,
}) => {
  return (
    <div className="item-form">
      <h2>{formValues.id ? "Editar" : "Crear"}</h2>
      {fields
        .filter((field) => !field.autoGenerated)
        .map((field) => (
          <div className="form-group" key={field.name}>
            <label>{field.label}:</label>
            <input
              type={
                field.type === "password" && field.showPassword
                  ? "text"
                  : field.type
              }
              name={field.name}
              value={formValues[field.name] || ""}
              onChange={onChange}
            />
            {formErrors[field.name] && (
              <div className="error-message">{formErrors[field.name][0]}</div>
            )}
          </div>
        ))}
      <div className="form-actions">
        <button onClick={onSave}>Guardar</button>
        <button onClick={onCancel}>Cancelar</button>
      </div>
    </div>
  );
};

export default CRUDForm;

