// Baseball_Management/src/components/FormulariosCRUD/BaseCRUD/CRUDForm.jsx

import React from "react";

const CRUDForm = ({
    fields,
    formValues,
    formErrors,
    onChange,
    onSave,
    onCancel,
}) => {
    const title = formValues.id ? "Editar registro" : "Registrar nuevo";

    return (
        <div className="bc-form">
            <div className="bc-form__head">
                <div>
                    <span className="bc-form__kicker">
                        {formValues.id ? "Modo edición" : "Nuevo registro"}
                    </span>
                    <h3 className="bc-form__title">{title}</h3>
                </div>
            </div>

            <div className="bc-form__body">
                {formErrors.detail && (
                    <div className="error-message error-general">{formErrors.detail}</div>
                )}

                {fields
                    .filter((field) => !field.autoGenerated)
                    .map((field) => (
                        <div className="form-group bc-form__group" key={field.name}>
                            <label className="bc-form__label">{field.label}:</label>

                            {field.type === "password" ? (
                                <div className="password-container">
                                    <input
                                        type={field.showPassword ? "text" : "password"}
                                        name={field.name}
                                        value={formValues[field.name] || ""}
                                        onChange={onChange}
                                        className="bc-form__input"
                                    />
                                    {field.toggleVisibility && (
                                        <button
                                            type="button"
                                            onClick={field.toggleVisibility}
                                            className="toggle-password bc-form__toggle"
                                        >
                                            {field.showPassword ? "Ocultar" : "Mostrar"}
                                        </button>
                                    )}
                                </div>
                            ) : field.type === "select" ? (
                                <select
                                    name={field.name}
                                    value={formValues[field.name] || ""}
                                    onChange={onChange}
                                    className="bc-form__input bc-form__select"
                                >
                                    <option value="">Seleccione una opción</option>
                                    {field.options.map((option) => (
                                        <option key={option.id} value={option.id}>
                                            {option.name}
                                        </option>
                                    ))}
                                </select>
                            ) : (
                                <input
                                    type={field.type}
                                    name={field.name}
                                    value={formValues[field.name] || ""}
                                    onChange={onChange}
                                    className="bc-form__input"
                                />
                            )}

                            {formErrors[field.name] && (
                                <div className="error-message">{formErrors[field.name][0]}</div>
                            )}
                        </div>
                    ))}
            </div>

            <div className="bc-form__actions">
                <button className="bc-form__btn bc-form__btn--primary" onClick={onSave}>
                    Guardar
                </button>
                <button className="bc-form__btn bc-form__btn--ghost" onClick={onCancel}>
                    Cancelar
                </button>
            </div>
        </div>
    );
};

export default CRUDForm;